[package]
name = "order"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
log = "0.4.17"
env_logger = "0.9.1"
camunda-external-task-client-rust = { path = "../.." }
serde_json = "1.0.86"
chrono = "0.4.22"
